language: ruby
rvm:
- 2.1.2
cache: bundler
addons:
  postgresql: '9.3'
before_script:
- bundle exec rake db:create
deploy:
  provider: heroku
  app:
    master: irb-sample-app
  on:
    repo: Capncavedan/irb-sample-app
  run: rake db:migrate
  api_key:
    secure: S2pDtWN5knP2+7Tp29gEQ/xNd8SdiKHG9qhrXNtKQJRvzhSw82CQFqm44Ub9RWvm7qOxgYqFVKZZ4qX+X+nZDvMvH0qSedSonQIwa/BvQdX5s5Gti54x6cK1acoaTnBCZo7fypVFNAMnxohx95JZjjInyoIBct5iww1daLwZymo=
